exclude: ^(.bzr|\.direnv|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.pants\.d|\.svn|\.tox|\.venv|_build|buck-out|build|dist|node_modules|venv|\.idea|dockerdata|static|.*\b(migrations)\b.*)
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear==20.1.4
        - flake8-builtins==1.5.3
        - flake8-comprehensions==3.2.3
        - flake8-tidy-imports==4.1.0
        - flake8-eradicate==1.1.0
        - flake8-print==4.0.0
        - flake8-return==1.1.2
        - flake8-use-fstring==1.1
        - git+https://github.com/derrix060/flake8-expression-complexity.git
