[tool.black]
line-length = 121
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
# regex below includes default list from isort, for parity
exclude = '''
/(
    \.bzr
  | \.direnv
  | \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.pants\.d
  | \.svn
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | node_modules
  | venv
  | \.idea
  | dockerdata
  | static
)/
'''

[tool.isort]
# these are black-compatible settings
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 121
skip = "dockerdata,.idea,static"
filter_files = true
